### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/page.codeberg.DrRac27.Karoto#4]
https://codeberg.org/DrRac27/karoto/src/branch/main/packaging/karoto.desktop has none

 Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by DrRac27** [comment]
Like this? https://codeberg.org/DrRac27/karoto/commit/58e96e8865706c941fed74e46457e589d0a0f5d8

**Comment by bbhtt** [comment]
Yes seems fine.

**Comment by DrRac27** [comment]
Thank you!
